# Base
base_texture : &base-texture
  texture_type: color
  color: [0, 150, 150]

# Body parts
base: &base
  physical_shape: circle
  texture:  *base-texture
  radius: 13
  mass: 20
  max_linear_velocity: 1.0
  max_angular_velocity: 0.25

head_texture : &head-texture
  texture_type: color
  color: [0, 180, 150]

head: &head
  texture:  *head-texture
  physical_shape: circle
  mass: 5
  radius: 8
  max_angular_velocity: 0.25
  rotation_range: 90




#arms_texture : &arms-texture
#  texture_type: color
#  color: [0, 150, 170]
#
#
#

#
#arm: &arm
#  texture:  *arms-texture
#  radius: 10
#  mass: 1
#  rotation_speed: 0.25
#  rotation_range: 60
#  metabolism: 0.001
