# Base
base_texture : &base-texture
  texture_type: color
  color: [0, 150, 150]

# Body parts
base: &base
  physical_shape: circle
  texture:  *base-texture
  radius: 10
  mass: 30
  max_linear_velocity: 1.0
  max_angular_velocity: 0.25


#head_texture : &head-texture
#  texture_type: color
#  color: [0, 180, 150]
#
#arms_texture : &arms-texture
#  texture_type: color
#  color: [0, 150, 170]
#
#
#
#head: &head
#  texture:  *head-texture
#  radius: 4
#  rotation_speed: 0.25
#  rotation_range: 180
#  metabolism : 0.001
#  mass: 1
#
#arm: &arm
#  texture:  *arms-texture
#  radius: 10
#  mass: 1
#  rotation_speed: 0.25
#  rotation_range: 60
#  metabolism: 0.001
