# Default Configuration file for Zones

# Termination Zones

deathzone_texture : &deathzone-texture
  texture_type: color
  color: [225, 10, 10]

death_zone :
  physical_shape: square
  radius: 15
  texture: *deathzone-texture
  reward: -200

goalzone_texture : &goalzone-texture
  texture_type: color
  color: [10, 255, 10]

goal_zone :
  physical_shape: square
  radius: 15
  texture: *goalzone-texture
  reward: 200


# Reward Zones

toxiczone_texture : &toxiczone-texture
  texture_type: color
  color: [250, 250, 0]

toxic_zone :
  physical_shape: square
  radius: 15
  texture: *toxiczone-texture
  reward: -1
  total_reward: -1000000

healingzone_texture : &healingzone-texture
  texture_type: color
  color: [0, 250, 250]

healing_zone :
  physical_shape: square
  radius: 15
  texture: *healingzone-texture
  reward: 1
  total_reward: 100000



#
#healing_zone_texture : &healingzone-texture
#    'type': 'color'
#    'color': (0, 0, 250)
#
#healing_zone_default :
#    'entity_type':'reward_zone'
#    'texture': *healingzone-texture
#    'reward': 2
#    'total_reward': 200
#
#damaging_zone_texture : &damagingzone-texture
#    'type': 'color'
#    'color': (250, 250, 0)
#
#damaging_zone_default :
#    'entity_type':'reward_zone'
#    'texture': *damagingzone-texture
#    'reward': -2
#    'total_reward': -200
#
#
#
## Basic entities
#
#door_texture =  {
#    'type': 'random_tiles',
#    'min': [110, 110, 110],
#    'max': [130, 130, 130],
#    'size_tiles' : 10
#    }
#
#door_default = {
#    'entity_type': 'basic',
#    'physical_shape': 'rectangle',
#    'shape_rectangle': [10, 100],
#    'texture': door_texture.copy(),
#    'movable': False
#}
#
#button_door_openclose_texture =  {
#    'type': 'color',
#    'color': (50, 100, 150)
#    }
#
#button_door_openclose_default = {
#    'entity_type': 'button_door_openclose',
#    'door': door_default.copy(),
#    'physical_shape': 'square',
#    'radius': 10,
#    'texture': button_door_openclose_texture.copy(),
#    'movable': False,
#    'interaction_range': 10,
#}
#
#button_door_opentimer_texture =  {
#    'type': 'color',
#    'color': (50, 100, 150)
#    }
#
#button_door_opentimer_default = {
#    'entity_type': 'button_door_opentimer',
#    'door': door_default.copy(),
#    'physical_shape': 'square',
#    'radius': 10,
#    'texture': button_door_opentimer_texture.copy(),
#    'movable': False,
#    'interaction_range': 10,
#    'time_open': 50
#}
#
#
#lock_key_door_texture =  {
#    'type': 'color',
#    'color': (50, 100, 150)
#    }
#
#lock_key_door_default = {
#    'entity_type': 'lock_key_door',
#    'door': door_default.copy(),
#    'physical_shape': 'square',
#    'radius': 10,
#    'texture': lock_key_door_texture.copy(),
#    'movable': False,
#    'interaction_range': 10,
#
#    'key':
#        {
#            'entity_type': 'gem',
#            'physical_shape': 'circle',
#            'radius': 5,
#            'mass': 10,
#            'texture': lock_key_door_texture.copy(),
#            'movable': True,
#            'graspable': True,
#            'interaction_range': 10,
#        }
#
#
#}
#
########
#fireball_texture =  {
#    'type': 'centered_random_tiles',
#    'min': [200, 0, 0],
#    'max': [255, 100, 0],
#    'size_tiles' : 4
#    }
#
#fireball_default = {
#
#    'texture': fireball_texture.copy(),
#    'entity_type':'fireball',
#    'interaction_range': 10,
#    'reward': -2,
#    'total_reward': -200,
#
#    'physical_shape': 'circle',
#    'radius': 10,
#    'mass': 10,
#    'movable': True
#}
#
#fairy_texture =  {
#    'type': 'centered_random_tiles',
#    'min': [0, 150, 200],
#    'max': [0, 200, 250],
#    'size_tiles' : 3
#    }
#
#fairy_default = {
#
#    'texture': fairy_texture.copy(),
#    'entity_type':'fairy',
#    'interaction_range': 10,
#    'reward': 2,
#    'total_reward': 200,
#
#    'physical_shape': 'circle',
#    'radius': 10,
#    'mass': 10,
#    'movable': True
#}
#
#
#key_chest_texture =  {
#    'type': 'color',
#    'color': (50, 100, 150)
#    }
#
#
#key_chest_default = {
#            'entity_type': 'gem',
#            'physical_shape': 'square',
#            'radius': 10,
#            'mass': 20,
#            'texture': key_chest_texture.copy(),
#            'movable': True,
#            'graspable': True,
#            'interaction_range': 10,
#        }
#
#chest_texture =  {
#    'type': 'color',
#    'color': (70, 180, 200)
#    }
#
#
#chest_default = {
#
#    'physical_shape': 'square',
#    'radius': 20,
#    'movable': False,
#    'interaction_range': 10,
#
#    'texture': chest_texture.copy(),
#    'entity_type': 'chest',
#    'reward': 50,
#
#    'key_pod': key_chest_default.copy()
#}